#제품모드
[build]
command = "npm run dev"
functions = "functions"
publish = "dist"

#개발모드
[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 8080
port = 8888
publish = 'dist'
autoLaunch = true